CREATE TABLE TBL_OWNER (
                           PROVIDER_ID VARCHAR2(255) PRIMARY KEY,
                           PROVIDER VARCHAR2(50),
                           OWNER_NAME VARCHAR2(100),
                           OWNER_AGE NUMBER,
                           OWNER_LICENCE VARCHAR2(100),
                           OWNER_PHONE_NUMBER VARCHAR2(100),
                           OWNER_ADDRESS VARCHAR2(255),
                           OWNER_JOB VARCHAR2(100),
                           PROFILE_PIC VARCHAR2(255),
                           ROLE VARCHAR2(10)
);

CREATE TABLE TBL_CAR (
                         CAR_ID NUMBER PRIMARY KEY,
                         CAR_NUMBER VARCHAR2(100),
                         CAR_MODEL VARCHAR2(100),
                         CAR_CHARGING_TYPE VARCHAR2(100),
                         PROVIDER_ID VARCHAR2(255),
                         INSURER_ID NUMBER,
                         CURRENT_LOCATION VARCHAR2(200),
                         CURRENT_BATTERY NUMBER,
                         CURRENT_STATUS VARCHAR2(50),
                         FOREIGN KEY (PROVIDER_ID) REFERENCES TBL_OWNER(PROVIDER_ID),
                         FOREIGN KEY (INSURER_ID) REFERENCES TBL_INSURER(INSURER_ID)
);

ALTER TABLE TBL_CAR
    ADD (
        CURRENT_LATITUDE NUMBER(10, 6),
        CURRENT_LONGITUDE NUMBER(10, 6)
        );



ALTER TABLE TBL_CAR
    ADD CAR_IMAGE_FILE_ID INT;

ALTER TABLE TBL_CAR
    DROP COLUMN CAR_IMAGE_PATH;

ALTER TABLE TBL_CAR
    ADD CAR_IMAGE_FILE_NAME VARCHAR2(255);

ALTER TABLE TBL_CAR
    DROP COLUMN CAR_IMAGE_FILE_ID;

UPDATE TBL_CAR
SET CURRENT_LATITUDE = ROUND(37.5575753, 6), CURRENT_LONGITUDE = ROUND(127.0466899, 6)
WHERE CAR_ID = 17;




ALTER TABLE TBL_CAR ADD CAR_NAME VARCHAR2(100);
ALTER TABLE TBL_CAR ADD CAR_IMAGE_PATH VARCHAR2(255);

ALTER TABLE TBL_CAR
    DROP COLUMN CURRENT_LOCATION;

SELECT CURRENT_LATITUDE, CURRENT_LONGITUDE
FROM TBL_CAR
WHERE CAR_ID = :carId;


CREATE TABLE TBL_INSURER (
                             INSURER_ID NUMBER PRIMARY KEY,
                             INSURE_NUMBER VARCHAR2(100),
                             INSURER_NAME VARCHAR2(100),
                             INSURER_PHONE_NUMBER VARCHAR2(100),
                             INSURER_REQUEST VARCHAR2(100)
);

CREATE TABLE TBL_INQUIRY (
                             INQUIRY_ID NUMBER PRIMARY KEY,
                             INQUIRY_TITLE VARCHAR2(200),
                             INQUIRY_CONTENT VARCHAR2(2000),
                             INQUIRY_VIEW NUMBER,
                             INQUIRY_REGISTER_DATE DATE,
                             INQUIRY_UPDATE_DATE DATE,
                             PROVIDER_ID VARCHAR2(255),
                             FOREIGN KEY (PROVIDER_ID) REFERENCES TBL_OWNER(PROVIDER_ID)
);

ALTER TABLE TBL_INQUIRY
    ADD REQUEST_ID NUMBER;

ALTER TABLE TBL_INQUIRY
    ADD CONSTRAINT FK_REQUEST_ID FOREIGN KEY (REQUEST_ID)
        REFERENCES TBL_CHARGING_REQUEST(REQUEST_ID);

ALTER TABLE TBL_INQUIRY
    ADD ACCIDENT VARCHAR2(100);


CREATE TABLE TBL_COMMENTS (
                              COMMENT_ID NUMBER PRIMARY KEY,
                              INQUIRY_ID NUMBER,
                              PROVIDER_ID VARCHAR2(255),
                              COMMENT_CONTENT VARCHAR2(2000),
                              COMMENT_REGISTER_DATE DATE,
                              COMMENT_UPDATE_DATE DATE,
                              FOREIGN KEY (INQUIRY_ID) REFERENCES TBL_INQUIRY(INQUIRY_ID),
                              FOREIGN KEY (PROVIDER_ID) REFERENCES TBL_OWNER(PROVIDER_ID)
);

CREATE TABLE TBL_FILES (
                           FILE_ID NUMBER PRIMARY KEY,
                           INQUIRY_ID NUMBER,
                           ORIGINAL_FILE_NAME VARCHAR2(200),
                           STORED_FILE_NAME VARCHAR2(200),
                           FILE_SIZE NUMBER,
                           UPLOAD_TIME DATE,
                           FOREIGN KEY (INQUIRY_ID) REFERENCES TBL_INQUIRY(INQUIRY_ID)
);

CREATE TABLE TBL_CHARGING_STATION (
                                      STATION_ID NUMBER PRIMARY KEY,
                                      STATION_ADDRESS VARCHAR2(200),
                                      STATION_PHONE_NUMBER VARCHAR2(100),
                                      STATION_NAME VARCHAR2(100)
);

ALTER TABLE TBL_CHARGING_STATION
    ADD (LATITUDE NUMBER,
         LONGITUDE NUMBER);



CREATE TABLE TBL_STATION_CHARGER (
                                     CHARGER_ID NUMBER PRIMARY KEY,
                                     STATION_ID NUMBER,
                                     CAR_CHARGING_TYPE VARCHAR2(100),
                                     CHARGER_STATUS VARCHAR2(50),
                                     FOREIGN KEY (STATION_ID) REFERENCES TBL_CHARGING_STATION(STATION_ID)
);

ALTER TABLE TBL_STATION_CHARGER ADD CHARGER_TYPE VARCHAR2(50);

CREATE TABLE TBL_CHARGING_REQUEST (
                                      REQUEST_ID NUMBER PRIMARY KEY,
                                      PROVIDER_ID VARCHAR2(255),
                                      CAR_ID NUMBER,
                                      CHARGING_PERMIT VARCHAR2(50),
                                      STATION_ID NUMBER,
                                      REQUEST_STATUS VARCHAR2(50),
                                      CHARGING_TIME DATE,
                                      CHARGE_AMOUNT NUMBER,
                                      FOREIGN KEY (PROVIDER_ID) REFERENCES TBL_OWNER(PROVIDER_ID),
                                      FOREIGN KEY (CAR_ID) REFERENCES TBL_CAR(CAR_ID),
                                      FOREIGN KEY (STATION_ID) REFERENCES TBL_CHARGING_STATION(STATION_ID)
);


CREATE TABLE TBL_CHARGING_SESSION (
                                      SESSION_ID NUMBER PRIMARY KEY,
                                      REQUEST_NUMBER NUMBER,
                                      CHARGING_START_TIME DATE,
                                      CHARGING_END_TIME DATE,
                                      CHARGE_AMOUNT NUMBER,
                                      FOREIGN KEY (REQUEST_NUMBER) REFERENCES TBL_CHARGING_REQUEST(REQUEST_ID)
);

CREATE TABLE TBL_DRIVING_INFO (
                                  DRIVING_ID NUMBER PRIMARY KEY,
                                  CAR_ID NUMBER,
                                  START_ADDRESS VARCHAR2(200),
                                  STATION_ID NUMBER,
                                  END_ADDRESS VARCHAR2(200),
                                  START_TIME DATE,
                                  END_TIME DATE,
                                  DRIVING_STATUS VARCHAR2(50),
                                  FOREIGN KEY (CAR_ID) REFERENCES TBL_CAR(CAR_ID),
                                  FOREIGN KEY (STATION_ID) REFERENCES TBL_CHARGING_STATION(STATION_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_OWNER_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


CREATE SEQUENCE SEQ_CAR_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE SEQ_INSURER_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

drop sequence SEQ_INQUIRY_ID;

CREATE SEQUENCE SEQ_INQUIRY_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

select *
from TBL_INQUIRY;

CREATE SEQUENCE SEQ_COMMENT_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE SEQ_FILE_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE SEQ_STATION_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE SEQ_CHARGER_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE SEQ_REQUEST_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE SEQ_SESSION_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE SEQ_DRIVING_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


ALTER TABLE TBL_OWNER RENAME COLUMN OWNER_JOB TO OWNER_TYPE;

// 충전소 데이터 추가
INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (2, '제주특별자치도 제주시 첨단로 242', '064-123-4567', '충전소 1', 33.450701, 126.570667);

INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (3, '제주특별자치도 제주시 첨단로 210', '064-234-5678', '충전소 2', 33.451701, 126.571667);


INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (1, 2, '급속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (2, 2, '완속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (3, 2, '급속', '충전 중');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (4, 2, '완속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (5, 3, '급속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (6, 3, '완속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (7, 3, '급속', '충전 중');

-- 새로운 충전소 데이터 삽입
INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (6, '서울특별시 강남구 테헤란로 123', '02-123-4567', '충전소 3', 37.498095, 127.027610);

-- 새로운 충전기 데이터 삽입
INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (15, 6, '급속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (16, 6, '완속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (17, 6, '급속', '충전 중');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (18, 6, '완속', '사용 가능');


-- 충전소 4 데이터 삽입
INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (7, '서울특별시 중구 세종대로 110', '02-789-1234', '충전소 4', 37.566535, 126.977969);

-- 충전소 5 데이터 삽입
INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (8, '서울특별시 강남구 삼성로 512', '02-345-6789', '충전소 5', 37.508255, 127.063351);

-- 충전소 6 데이터 삽입
INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (9, '서울특별시 마포구 월드컵북로 396', '02-567-8901', '충전소 6', 37.568276, 126.898495);

-- 충전소 7 데이터 삽입
INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (10, '서울특별시 송파구 올림픽로 25', '02-678-9012', '충전소 7', 37.514876, 127.105916);

-- 충전소 4 충전기 데이터 삽입
INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (19, 7, '급속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (20, 7, '완속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (21, 7, '급속', '충전 중');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (22, 7, '완속', '사용 가능');

-- 충전소 5 충전기 데이터 삽입
INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (23, 8, '급속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (24, 8, '완속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (25, 8, '급속', '충전 중');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (26, 8, '완속', '사용 가능');

-- 충전소 6 충전기 데이터 삽입
INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (27, 9, '급속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (28, 9, '완속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (29, 9, '급속', '충전 중');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (30, 9, '완속', '사용 가능');

-- 충전소 7 충전기 데이터 삽입
INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (31, 10, '급속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (32, 10, '완속', '사용 가능');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (33, 10, '급속', '충전 중');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS)
VALUES (34, 10, '완속', '사용 가능');

--
-- 충전소 2의 모든 충전기 타입을 CCS1으로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'CCS1' WHERE STATION_ID = 2;

-- 충전소 3의 모든 충전기 타입을 Type 2로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Type 2' WHERE STATION_ID = 3;

-- 충전소 6의 모든 충전기 타입을 Tesla Supercharger로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Tesla Supercharger' WHERE STATION_ID = 6;

-- 충전소 7의 모든 충전기 타입을 CHAdeMO로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'CHAdeMO' WHERE STATION_ID = 7;

-- 충전소 8의 모든 충전기 타입을 GB/T로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'GB/T' WHERE STATION_ID = 8;

-- 충전소 9의 모든 충전기 타입을 CCS2로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'CCS2' WHERE STATION_ID = 9;

-- 충전소 10의 모든 충전기 타입을 Type 2로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Type 2' WHERE STATION_ID = 10;


----
-- 충전소 2의 모든 급속 충전기를 CCS1으로, 완속 충전기를 Type 1으로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'CCS1' WHERE STATION_ID = 2 AND CAR_CHARGING_TYPE = '급속';
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Type 1' WHERE STATION_ID = 2 AND CAR_CHARGING_TYPE = '완속';

-- 충전소 3의 모든 급속 충전기를 CCS2로, 완속 충전기를 Type 2로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'CCS2' WHERE STATION_ID = 3 AND CAR_CHARGING_TYPE = '급속';
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Type 2' WHERE STATION_ID = 3 AND CAR_CHARGING_TYPE = '완속';

-- 충전소 6의 모든 급속 충전기를 Tesla Supercharger로, 완속 충전기를 Type 2로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Tesla Supercharger' WHERE STATION_ID = 6 AND CAR_CHARGING_TYPE = '급속';
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Type 2' WHERE STATION_ID = 6 AND CAR_CHARGING_TYPE = '완속';

-- 충전소 7의 모든 급속 충전기를 CHAdeMO로, 완속 충전기를 Type 2로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'CHAdeMO' WHERE STATION_ID = 7 AND CAR_CHARGING_TYPE = '급속';
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Type 2' WHERE STATION_ID = 7 AND CAR_CHARGING_TYPE = '완속';

-- 충전소 8의 모든 급속 충전기를 GB/T로, 완속 충전기를 Type 2로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'GB/T' WHERE STATION_ID = 8 AND CAR_CHARGING_TYPE = '급속';
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Type 2' WHERE STATION_ID = 8 AND CAR_CHARGING_TYPE = '완속';

-- 충전소 9의 모든 급속 충전기를 CCS2로, 완속 충전기를 Type 2로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'CCS2' WHERE STATION_ID = 9 AND CAR_CHARGING_TYPE = '급속';
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Type 2' WHERE STATION_ID = 9 AND CAR_CHARGING_TYPE = '완속';

-- 충전소 10의 모든 급속 충전기를 CCS1로, 완속 충전기를 Type 1로 업데이트
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'CCS1' WHERE STATION_ID = 10 AND CAR_CHARGING_TYPE = '급속';
UPDATE TBL_STATION_CHARGER SET CHARGER_TYPE = 'Type 1' WHERE STATION_ID = 10 AND CAR_CHARGING_TYPE = '완속';

-----------------------
-- 충전소 데이터 추가
INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (11, '서울특별시 강서구 화곡로 123', '02-111-2222', '충전소 8', 37.553845, 126.837579);

INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (12, '서울특별시 강북구 도봉로 456', '02-333-4444', '충전소 9', 37.648606, 127.034601);

INSERT INTO TBL_CHARGING_STATION (STATION_ID, STATION_ADDRESS, STATION_PHONE_NUMBER, STATION_NAME, LATITUDE, LONGITUDE)
VALUES (13, '서울특별시 강동구 천호대로 789', '02-555-6666', '충전소 10', 37.538377, 127.147675);

-- 충전기 데이터 추가
INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS, CHARGER_TYPE)
VALUES (35, 11, '급속', '사용 가능', 'CCS1');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS, CHARGER_TYPE)
VALUES (36, 11, '완속', '사용 가능', 'Type1');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS, CHARGER_TYPE)
VALUES (37, 12, '급속', '충전 중', 'CHAdeMO');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS, CHARGER_TYPE)
VALUES (38, 12, '완속', '사용 가능', 'Type2');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS, CHARGER_TYPE)
VALUES (39, 13, '급속', '사용 가능', 'Tesla Supercharger');

INSERT INTO TBL_STATION_CHARGER (CHARGER_ID, STATION_ID, CAR_CHARGING_TYPE, CHARGER_STATUS, CHARGER_TYPE)
VALUES (40, 13, '완속', '사용 가능', 'GB/T');

ALTER TABLE TBL_CHARGING_REQUEST ADD CHARGING_START_TIME DATE;
ALTER TABLE TBL_CHARGING_REQUEST ADD CHARGING_END_TIME DATE;
ALTER TABLE TBL_CHARGING_REQUEST ADD CHARGE_AMOUNT NUMBER(100);
ALTER TABLE TBL_CHARGING_REQUEST DROP COLUMN CHARGE_AMOUNT;

DROP TABLE TBL_CHARGING_SESSION
